name: Build LaTeX document

on: 
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - master



jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document Introduction
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Introduction/

      - name: Compile LaTeX document Stability
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Stability/

      - name: Compile LaTeX document Laplace
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Laplace/

      - name: Compile LaTeX document Control
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Control/

      - name: Compile LaTeX document Discrete
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Discrete/






      - name: Save Introduction artifact
        uses: actions/upload-artifact@v1
        with:
          name: Introduction.pdf
          path: Slides/Introduction/main.pdf


      - name: Save Stability artifact
        uses: actions/upload-artifact@v1
        with:
          name: Stability.pdf
          path: Slides/Stability/main.pdf


      - name: Save Laplace artifact
        uses: actions/upload-artifact@v1
        with:
          name: Laplace.pdf
          path: Slides/Laplace/main.pdf

      - name: Save Control artifact
        uses: actions/upload-artifact@v1
        with:
          name: Control.pdf
          path: Slides/Control/main.pdf

      - name: Save Discrete artifact
        uses: actions/upload-artifact@v1
        with:
          name: Discrete.pdf
          path: Slides/Discrete/main.pdf


      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add Slides/Introduction/main.pdf
          git add Slides/Stability/main.pdf
          git add Slides/Laplace/main.pdf
          git add Slides/Control/main.pdf
          git add Slides/Discrete/main.pdf




          git commit -m "Update compiled PDFs"
          git push
